# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_user_provider:
            entity:
                class: AppBundle\Entity\User
                property: email

    encoders:
        AppBundle\Entity\User: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous:  ~ # can be omitted as its default value
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            provider: db_user_provider
            logout:
                path: /logout
                target: /


    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/settings, roles: [ IS_AUTHENTICATED_FULLY ] }